services:
  db:
    image: postgres:16
    container_name: factory-db
    environment:
      POSTGRES_DB: factory_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: factory-backend
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/factory_db
      QUARKUS_FLYWAY_MIGRATE_AT_START: "true" 
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: factory-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080/api